## FUNCTIONS IN DEPTH

There are two types of functions
- **built-in** (already written in Standard Python that we can use)
- **custom** (you can write your own functions, which is essentially little blocks of code that you can then re-use in your program if needed)

Let's look at **built-in functions** first. We have already seen a few built-in functions:
- `print()`
- `type()`
- `int()`, `str()`, `bool()`, `float()`

<u> Function names are always followed by () parentheses</u>

<u>Functions accept one or more parameters or inputs.</u>

Functions accept one or more inputs (known as **parameters**, and the values we pass to the parameters are known as **arguments**). 

Some parameters have *default values* (indicated by a `=` after the parameter name), and others do not.

If a parameter does not have a default value, then that is a *required* parameter (also known as **positional parameters** - since they are always listed first) and we have to provide that value as an input when we call the function. Below, input1 and input2 are a positional parameters. 

`function_name (input1)` \
`function_name (input1, input2)`

If parameters have default values (known as **keyword parameters**), we can choose to use them (and in that case, we dont have to pass it any arguments/values), or we can change the default values if we wish, by calling param_name = new_arg_value. Here is how we can set a new value for a parameter named input3.

`function_name (input1, input2, input3 = val3)`

Note that positional parameters are always listed first, before the keyword parameters.


<u>Functions may have a return type.</u>

A function may **return** a value and if it does, the docustring will mention the word *return*. If so, it is common to save the returned value.

`answer = function_name(input)`

Othertimes, functions return `None` (Python for nothing). Here we would just call the function without trying to save the returned value (since there is None).

`function_name(input)`

### A deeper look at the `print()` function as a representative built-in function

Obtain the docstring (documentation) by using `?` after the function name. Please read it. All functions work the same way.

**1. What parameters does print() have? and what are their default values?**
- value
- sep (= ' ')
- end (= '\n')
- file (= sys.stdout (that means the output is sent to the console) 
- flush (= False)

Value is the only positional parameter, since it is followed by ..., it means that there can be many values provided. All the rest are keyword parameters.

**2. Does it have a return value?**\
No. If it does, the dostring would mention the word **return**. print() returns None (equal to nothing in Python).

In [71]:
# Uncomment the following line to obtain the documentation
# print?

In [75]:
# we can provide the function with multiple values (positional parameters)
print("butter", "jam")
print("bread", "milk")

# we can optionally change the values of kewyord parameters sep and end.
# by default end always ends the printed output with \n - a newline character.
# We can change it to a tab \t
# the default sep is a space ' ' between values. We can change it.
print("butter", "jam" , sep = ' * ', end ="\t")
print("bread", "milk", sep = ' + ')

butter jam
bread milk
butter * jam	bread + milk

## OBJECTS - CLASS AND METHODS

In Python, we have something known as classes. They are templates from which we can create children known as **objects**.

For example, when we create string data, what we create is actually a str object (from the str class).

Classes are important because they provide us with **methods** - which help to manipulate or operate on the content of the object.

Methods are called as follows - using the **`.`** (dot) operator : \

`objectname.methodname()`

Methods have the same format as functions:
- the methodname is followed by ()
- inside (), we can specify arguments or inputs for positional and keyword parameters, if any
- if the method returns a value, we can save it

Methods differ from functions:
- methods use a dot operator, functions do not
- methods are called from an object of a class, functions are not

### String methods

Let us take a look at the **`str`** class and its methods. **`str`** class helps us to store and manipulate string or text data.

In [3]:
# here mystr is an object of the str class
mystr = "we are learning python"

print(mystr.upper())

print(mystr.capitalize())

print(mystr.count("a"))

WE ARE LEARNING PYTHON
We are learning python
2

Notice that as you type commands with methods, the docstring is automatically pulled up.

How to read the docstring?

`Docstring:`\
`S.count(sub[, start[, end]]) -> int`

* anything inside the () are parameters
* the first parameter is sub and since it is not within [] - it means it is a positional required parameter. we have to specify what substring we want to count
* any parameters given inside [] means that they are keyword parameters with default values , so they are optional.
* you can change the keyword parameters by assigning them new values.
* -> indicates a return value
* the word after -> indicates th data type of the returned value.

In [10]:
# count the number of occurrences of substring "ar" 
# between index 3 and 7-1=6 of mystr
print(mystr.count("ar", 0, 4))

print(mystr.count("ar", 3, 7))

0
1

In [19]:
# since str.count() method returns an int, it is also useful to 
# save the returned value so that we can retrieve it later
# without needing to recalculate it

answer = mystr.count("ar")
print(answer)

2

## LISTS

Say we want to compute the average of 3 numbers, we can store these 3 numbers in 3 variables and then add to obtain the sum and then divide by 3.

In [2]:
num1 = 10
num2 = 20
num3 = 35

avg = ( num1+num2+num3)/3
print(avg)

21.666666666666668

But this is tedious. What if we had many more data points?

How about storing them in a collection - with a single name. Recall that the name of a variable refers to a specific memory location (here, it will refer to the first number, and all others can be found once we know the first).

Such a collection exists in Python, and it is called a **list**

In [55]:
stock_prices = [2865.0, 178.96, 1099.57, 40.69, 51.25, 3386.30, 147.23, 175.52]

List can contain any type of data.

In [36]:
stock_names = ['GOOG','AAPL', 'TSLA', 'TWTR', 'VZ', 'AMZN', 'WMT' , 'ABNB']

amixedlist = ['a','b', 'c', 1, 2, 3, True, 8.2] 

print(amixedlist)

['a', 'b', 'c', 1, 2, 3, True, 8.2]

### Apply some <u>built-in functions </u> to Lists

#### Length of a list

To obtain the length of a collection such as list, we can use:\
`len(collection)`

#### min and max of a list

`min(collection)` \
`max(collection)`

#### sorting a collection
`sorted(collection)`

In [64]:
print(len(stock_prices))

print(max(stock_prices))

print(min(stock_prices))

print(sorted(stock_prices))

8
3386.3
40.69
[40.69, 51.25, 147.23, 175.52, 178.96, 1099.57, 2865.0, 3386.3]

### Indexing a list

Each element has an **index**, that starts at 0. We can use **indexing** - and there are many forms of it - to obtain specific values from a list.

We can also use *reverse indexing* : the last element is at index -1.

In [5]:
stock_prices[0]

100.5

In [6]:
stock_prices[-1]

48

We can apply **slicing** to pick out multiple elements from the list, they dont have to be contiguous, we can also specify a step size to skip some. It will start at startindex (or index 0) but stop at endindex-1 (endindex is not inclusive, default is len(list)-1) and stepsize default = 1. 

If one of the index or stepsize is not given, the defaults are used.

`listname[startindex: endindex= : stepsize]`

In [13]:
# output every other element
stock_prices[ : : 2]

[2865.0, 1099.57, 51.25, 147.23]

In [11]:
# output the stock names in reverse
stock_names[: : -1]

['WMT', 'AMZN', 'VZ', 'TWTR', 'TSLA', 'AAPL', 'GOOG']

In [28]:
# output the first two values 
stock_names[ : 2]

['GOOG', 'AAPL']

### Appending or adding elements to a list

1.   **`+`** operator - adds items from a second  list to the first list, but doesnt change the first list, creates a new list

2.   use the **`.append()`** method of list. This adds the entire item to the list in-place (changes the original list)

3. use the **`.extend()`** method of list. This takes another list of elements and adds each element from the second list to the first list in-place.

In [37]:
stock_names + ['DOMO']

['GOOG', 'AAPL', 'TSLA', 'TWTR', 'VZ', 'AMZN', 'WMT', 'ABNB', 'DOMO']

In [39]:
stock_names

['GOOG', 'AAPL', 'TSLA', 'TWTR', 'VZ', 'AMZN', 'WMT', 'ABNB']

In [50]:
stock_prices.append(100)
stock_prices

[2865.0,
 178.96,
 1099.57,
 40.69,
 51.25,
 3386.3,
 147.23,
 175.52,
 51.85,
 (100, 200),
 100]

In [42]:
stock_prices.extend([51.85])
stock_prices

[2865.0, 178.96, 1099.57, 40.69, 51.25, 3386.3, 147.23, 175.52, 51.85]

### Deleting an element from a list

In [47]:
del(stock_prices[9])
stock_prices

[2865.0, 178.96, 1099.57, 40.69, 51.25, 3386.3, 147.23, 175.52, 51.85]

Deleting elements from a list

## LIST OF LISTS

Sometimes it may make sense to group some of the data in lists instead of creating a flat collection.

We can create many lists within a outer list. This is very similar to a table - with two indices - the first is the **row** and the second is the **column**

If you specify only one index (the rowindex, it will obtain the entire list. \
`listname[rowindex]` 

If you specify both indices, we will get a particular element within the sub-list.\
`listname[rowindex, colindex]`

In [27]:
stocks_and_prices = [['GOOG',2865.0], 
                     ['AAPL', 178.96], 
                     ['TSLA', 1099.57]]

print(stocks_and_prices[0])
print(stocks_and_prices[0][1])

['GOOG', 2865.0]
2865.0

## LOOPS

Sometimes, we may want to print out each element in a collection one by one (and not the whole collection itself). we can accomplish that using a loop - something that performs a said task iteratively.

We need to specify when to stop. For list, we can usually say as long as there are more elements, do something.

`for element in listname :`
    `#do something`
`

In [58]:
# let's print out each element from the list on the same line separated by '--'
for item in stock_names :
  print (item)

for item in stock_names :
  print (item, end = '--')

GOOG
AAPL
TSLA
TWTR
VZ
AMZN
WMT
ABNB
GOOG--AAPL--TSLA--TWTR--VZ--AMZN--WMT--ABNB--

In [56]:
# let's compute the average stock price
sum = 0.0
for item in stock_prices : 
  sum = sum +item
print("The average stock price in the list = ", sum/len(stock_prices))

The average stock price in the list =  993.0649999999999

## CONDITIONALS (IF-ELSE)

We use if-else statement to perform if-then-else operations.

The syntax is as follows:

`if (boolean condition) :`
    #write code to be run if condition is True. This has to be indented once
`else :`
    #write code to be run in condition is False. This has to be indented once

***Only code within one of the conditions will be executed, never more than one block will run***

Notice 
- the comment about *indentation*. Every line of code inside the if-condition has to be indented once and similarly, every line of code inside the else condition has to be indented once.
- the two conditions have to be followed by **`:`** (semi-colon)
- the conditions can be written inside **`()`** - it is optional, but good practice to use.

In [13]:
y = 10
z = 20
if (y > z) :
  print("y is greater than z")
else :
  print('y is less than z')

y is less than z

NOTE:

**`if`** does not need to be followed by an **`else`**. **`if`** can be written on its own.

To **check equality**, use the **`==`** operator. This is different from the **`=`** *italicized text* operator, which is an assignment operator that assigns the value on the right hand side to the variable on the left hand side.

To test for multiple **`if`** conditions, use **`elif`** for the second, third,....conditions. If followed by an **`else`** at the end, else block of code will act like a catch-all. If none of the above conditions is satisfied, then the code inside else will be executed.

***Only code within one of the conditions will be executed, never more than one block will run***

In [14]:
if (y > z):
  print("y is greater than z")
elif (y == z):
  print("y and z are the same")
else:
  print('y is less than z')

y is less than z

In [17]:
# we can also write multiple lines of code within each block
# make sure the are all indented once
# that is how python knows which lines go together in a block.
# all lines within each block will be executed if that condition is satisfied.

open = True

if (open == True) :
  print("the door is open.")
  close = False
else :
  print("the door is closed.")
  close = True

print(close)

the door is open.
False

## LIST COMPREHENSION (ADVANCED)

There is a shorthand notation for creating new lists by specifying a formula.

In [61]:
[item.lower() for item in stock_names]

['goog', 'aapl', 'tsla', 'twtr', 'vz', 'amzn', 'wmt', 'abnb']

## CHALLENGES OF LISTS

Since lists allow different data types, they are not always safe for data science operations.

Lists are not optimized - not the most efficient for computations - they are fine for small collections. But they require us to write loops (as shown above) to process each element. Loops are not efficient - they have a lot of overhead.

### So what else can we use?

We have **`arrays`** in the **numpy** module - which are optimized for calculations. 
- An array can only contain one type of data, and 
- we do not need to set up loops to perform operations on each element. Any operation will be automaticlaly applied on each element.

If we have tabular data, with rows and named columns, then we can use a module called **pandas**, which gives us **`DataFrames`** - essentially a table.
- each column is named and can be of different data types
- we can access entire rows, entire columns or subsets of row-cols.
- we dont need loops, the operation is performed on all of the selected location without needing explicit loops.
- very fast and efficient

## THE END